name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar SVG da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: JoaoGabrieloliv
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit do SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "generate snake animation"
          add: "dist/github-contribution-grid-snake.svg"

      - name: Push para a branch output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
